// <auto-generated />
namespace Projekt_Sisteme_Interneti.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lastModify : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastModify));
        
        string IMigrationMetadata.Id
        {
            get { return "202203221926376_lastModify"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
